version: "3"

services:
  db-service:
    image: mysql:8.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_USER=${WORDPRESS_DB_USER}

  wp-service:
    build: .
    env_file: ./.env
    command: bash -c 'install_wordpress && apache2-foreground'
    depends_on:
      - db-service
    ports:
      - "8080:8080"
    user: www-data
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
